language: python
# xenial required for python3.7+:
# https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
dist: xenial
cache: pip
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install tox-travis
script: tox